"use client";

import { useState, useEffect, useCallback } from "react";

// Storage key prefix for per-user language settings
const STORAGE_KEY_PREFIX = "profile-language-";

// Available languages
export const LANGUAGES = {
  en: { name: "English", nativeName: "English", flag: "🇬🇧" },
  es: { name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  fr: { name: "French", nativeName: "Français", flag: "🇫🇷" },
  de: { name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  pt: { name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  ja: { name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  ko: { name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  zh: { name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
} as const;

export type LanguageKey = keyof typeof LANGUAGES;

// Translations for all UI text
export const TRANSLATIONS: Record<LanguageKey, Record<string, string>> = {
  en: {
    // Settings Panel
    customizeProfile: "Customize Profile",
    displayMode: "Display Mode",
    darkMode: "Dark mode",
    lightMode: "Light mode",
    dark: "Dark",
    light: "Light",
    colorTheme: "Color Theme",
    fontStyle: "Font Style",
    featuredContent: "Featured Content",
    featuredNFTs: "Featured NFTs",
    chooseNFTs: "Choose which NFTs to showcase",
    featuredCast: "Featured Cast",
    pickCast: "Pick your best cast to display",
    custom: "Custom",
    language: "Language",
    selectLanguage: "Select your preferred language",

    // Gallery View
    featuredNFTsTitle: "Featured NFTs",
    topHoldings: "Top Holdings",
    topCast: "Top Cast",
    noNFTsFound: "No NFTs Found",
    noNFTsWallet: "This wallet doesn't have any NFTs yet",
    noVerifiedWallet: "No verified wallet address found",
    noFeaturedCast: "No featured cast selected",
    viewOnWarpcast: "View on Warpcast →",
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "days ago",
    weeksAgo: "weeks ago",
    monthsAgo: "months ago",
    yearsAgo: "years ago",

    // Cast Browser
    chooseCast: "Choose Top Cast",
    selectCastFeature: "Select a cast to feature on your profile",
    fetchingCasts: "Fetching top casts...",
    searched: "searched",
    showingTop: "Showing top",
    castsByEngagement: "casts by engagement",
    fromTotal: "from",
    total: "total",
    noCastsFound: "No Casts Found",
    noCastsEngagement: "No casts with engagement found yet",
    done: "Done",

    // Collection Browser
    selectNFTs: "Select NFTs",
    chooseUpTo: "Choose up to",
    nftsToFeature: "NFTs to feature",
    selected: "selected",
    loadingNFTs: "Loading NFTs...",
    noNFTsInWallet: "No NFTs found in this wallet",

    // Cast Translation
    translate: "Translate",
    showOriginal: "Show Original",
    translating: "Translating...",
    translationError: "Translation unavailable",

    // Projects Section
    myProjects: "My Projects",
    addProject: "Add Project",
    editProject: "Edit Project",
    projectTitle: "Project Title",
    projectDescription: "Description",
    projectUrl: "URL",
    projectType: "Type",
    website: "Website",
    miniapp: "Mini App",
    channel: "Channel",
    other: "Other",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    noProjects: "No projects added yet",
    addFirstProject: "Add your first project to showcase your work",
    manageProjects: "Add links to your projects",

    // Section Ordering
    sectionOrder: "Section Order",
    reorderSections: "Drag to reorder sections",
    resetOrder: "Reset",
    projectImage: "Preview Image",
    addManually: "Add manually",
    noImageYet: "No image yet",
    urlHelp: "Supports websites, mini apps, or Farcaster channels (/channel)",

    // About Me Section
    aboutMe: "About Me",
    editAboutMe: "Edit About Me",
    aboutMePlaceholder: "Tell people more about yourself, your interests, what you're working on, your story...",
    charactersRemaining: "characters remaining",
    noAboutMe: "No extended bio yet",
    addAboutMe: "Add a longer bio to tell your story",
  },
  es: {
    customizeProfile: "Personalizar Perfil",
    displayMode: "Modo de Pantalla",
    darkMode: "Modo oscuro",
    lightMode: "Modo claro",
    dark: "Oscuro",
    light: "Claro",
    colorTheme: "Tema de Color",
    fontStyle: "Estilo de Fuente",
    featuredContent: "Contenido Destacado",
    featuredNFTs: "NFTs Destacados",
    chooseNFTs: "Elige qué NFTs mostrar",
    featuredCast: "Cast Destacado",
    pickCast: "Elige tu mejor cast para mostrar",
    custom: "Personalizado",
    language: "Idioma",
    selectLanguage: "Selecciona tu idioma preferido",
    featuredNFTsTitle: "NFTs Destacados",
    topHoldings: "Principales Activos",
    topCast: "Mejor Cast",
    noNFTsFound: "No se encontraron NFTs",
    noNFTsWallet: "Esta cartera no tiene NFTs todavía",
    noVerifiedWallet: "No se encontró dirección verificada",
    noFeaturedCast: "No hay cast destacado seleccionado",
    viewOnWarpcast: "Ver en Warpcast →",
    today: "Hoy",
    yesterday: "Ayer",
    daysAgo: "días atrás",
    weeksAgo: "semanas atrás",
    monthsAgo: "meses atrás",
    yearsAgo: "años atrás",
    chooseCast: "Elegir Cast Principal",
    selectCastFeature: "Selecciona un cast para destacar",
    fetchingCasts: "Buscando casts...",
    searched: "buscados",
    showingTop: "Mostrando los",
    castsByEngagement: "casts más populares",
    fromTotal: "de",
    total: "total",
    noCastsFound: "No se encontraron Casts",
    noCastsEngagement: "No hay casts con interacciones aún",
    done: "Listo",
    selectNFTs: "Seleccionar NFTs",
    chooseUpTo: "Elige hasta",
    nftsToFeature: "NFTs para destacar",
    selected: "seleccionados",
    loadingNFTs: "Cargando NFTs...",
    noNFTsInWallet: "No hay NFTs en esta cartera",
    translate: "Traducir",
    showOriginal: "Mostrar Original",
    translating: "Traduciendo...",
    translationError: "Traducción no disponible",
    myProjects: "Mis Proyectos",
    addProject: "Agregar Proyecto",
    editProject: "Editar Proyecto",
    projectTitle: "Título del Proyecto",
    projectDescription: "Descripción",
    projectUrl: "URL",
    projectType: "Tipo",
    website: "Sitio Web",
    miniapp: "Mini App",
    channel: "Canal",
    other: "Otro",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    noProjects: "No hay proyectos aún",
    addFirstProject: "Agrega tu primer proyecto",
    manageProjects: "Agrega enlaces a tus proyectos",
    sectionOrder: "Orden de Secciones",
    reorderSections: "Arrastra para reordenar",
    resetOrder: "Restablecer",
    projectImage: "Imagen de Vista Previa",
    addManually: "Agregar manualmente",
    noImageYet: "Sin imagen aún",
    urlHelp: "Soporta sitios web, mini apps o canales (/canal)",
    aboutMe: "Sobre Mí",
    editAboutMe: "Editar Sobre Mí",
    aboutMePlaceholder: "Cuéntale a la gente más sobre ti, tus intereses, en qué estás trabajando...",
    charactersRemaining: "caracteres restantes",
    noAboutMe: "Sin biografía extendida aún",
    addAboutMe: "Agrega una biografía más larga para contar tu historia",
  },
  fr: {
    customizeProfile: "Personnaliser le Profil",
    displayMode: "Mode d'Affichage",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    dark: "Sombre",
    light: "Clair",
    colorTheme: "Thème de Couleur",
    fontStyle: "Style de Police",
    featuredContent: "Contenu en Vedette",
    featuredNFTs: "NFTs en Vedette",
    chooseNFTs: "Choisissez les NFTs à afficher",
    featuredCast: "Cast en Vedette",
    pickCast: "Choisissez votre meilleur cast",
    custom: "Personnalisé",
    language: "Langue",
    selectLanguage: "Sélectionnez votre langue",
    featuredNFTsTitle: "NFTs en Vedette",
    topHoldings: "Principaux Actifs",
    topCast: "Meilleur Cast",
    noNFTsFound: "Aucun NFT Trouvé",
    noNFTsWallet: "Ce portefeuille n'a pas encore de NFTs",
    noVerifiedWallet: "Aucune adresse vérifiée trouvée",
    noFeaturedCast: "Aucun cast sélectionné",
    viewOnWarpcast: "Voir sur Warpcast →",
    today: "Aujourd'hui",
    yesterday: "Hier",
    daysAgo: "jours",
    weeksAgo: "semaines",
    monthsAgo: "mois",
    yearsAgo: "ans",
    chooseCast: "Choisir le Cast Principal",
    selectCastFeature: "Sélectionnez un cast à mettre en avant",
    fetchingCasts: "Recherche des casts...",
    searched: "recherchés",
    showingTop: "Affichage des",
    castsByEngagement: "casts les plus populaires",
    fromTotal: "sur",
    total: "total",
    noCastsFound: "Aucun Cast Trouvé",
    noCastsEngagement: "Aucun cast avec des interactions",
    done: "Terminé",
    selectNFTs: "Sélectionner les NFTs",
    chooseUpTo: "Choisissez jusqu'à",
    nftsToFeature: "NFTs à mettre en avant",
    selected: "sélectionnés",
    loadingNFTs: "Chargement des NFTs...",
    noNFTsInWallet: "Aucun NFT dans ce portefeuille",
    translate: "Traduire",
    showOriginal: "Voir l'Original",
    translating: "Traduction...",
    translationError: "Traduction non disponible",
    myProjects: "Mes Projets",
    addProject: "Ajouter un Projet",
    editProject: "Modifier le Projet",
    projectTitle: "Titre du Projet",
    projectDescription: "Description",
    projectUrl: "URL",
    projectType: "Type",
    website: "Site Web",
    miniapp: "Mini App",
    channel: "Chaîne",
    other: "Autre",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    noProjects: "Aucun projet ajouté",
    addFirstProject: "Ajoutez votre premier projet",
    manageProjects: "Ajoutez des liens vers vos projets",
    sectionOrder: "Ordre des Sections",
    reorderSections: "Glisser pour réorganiser",
    resetOrder: "Réinitialiser",
    projectImage: "Image d'Aperçu",
    addManually: "Ajouter manuellement",
    noImageYet: "Pas encore d'image",
    urlHelp: "Sites web, mini apps ou chaînes Farcaster (/chaîne)",
    aboutMe: "À Propos de Moi",
    editAboutMe: "Modifier À Propos",
    aboutMePlaceholder: "Parlez de vous, de vos intérêts, de ce sur quoi vous travaillez...",
    charactersRemaining: "caractères restants",
    noAboutMe: "Pas encore de bio étendue",
    addAboutMe: "Ajoutez une bio plus longue pour raconter votre histoire",
  },
  de: {
    customizeProfile: "Profil Anpassen",
    displayMode: "Anzeigemodus",
    darkMode: "Dunkelmodus",
    lightMode: "Hellmodus",
    dark: "Dunkel",
    light: "Hell",
    colorTheme: "Farbthema",
    fontStyle: "Schriftstil",
    featuredContent: "Hervorgehobene Inhalte",
    featuredNFTs: "Hervorgehobene NFTs",
    chooseNFTs: "Wähle NFTs zum Anzeigen",
    featuredCast: "Hervorgehobener Cast",
    pickCast: "Wähle deinen besten Cast",
    custom: "Angepasst",
    language: "Sprache",
    selectLanguage: "Wähle deine Sprache",
    featuredNFTsTitle: "Hervorgehobene NFTs",
    topHoldings: "Top Bestände",
    topCast: "Bester Cast",
    noNFTsFound: "Keine NFTs Gefunden",
    noNFTsWallet: "Diese Wallet hat noch keine NFTs",
    noVerifiedWallet: "Keine verifizierte Adresse gefunden",
    noFeaturedCast: "Kein Cast ausgewählt",
    viewOnWarpcast: "Auf Warpcast ansehen →",
    today: "Heute",
    yesterday: "Gestern",
    daysAgo: "Tage",
    weeksAgo: "Wochen",
    monthsAgo: "Monate",
    yearsAgo: "Jahre",
    chooseCast: "Cast Auswählen",
    selectCastFeature: "Wähle einen Cast zum Hervorheben",
    fetchingCasts: "Lade Casts...",
    searched: "durchsucht",
    showingTop: "Zeige Top",
    castsByEngagement: "Casts nach Engagement",
    fromTotal: "von",
    total: "gesamt",
    noCastsFound: "Keine Casts Gefunden",
    noCastsEngagement: "Noch keine Casts mit Engagement",
    done: "Fertig",
    selectNFTs: "NFTs Auswählen",
    chooseUpTo: "Wähle bis zu",
    nftsToFeature: "NFTs zum Hervorheben",
    selected: "ausgewählt",
    loadingNFTs: "Lade NFTs...",
    noNFTsInWallet: "Keine NFTs in dieser Wallet",
    translate: "Übersetzen",
    showOriginal: "Original Zeigen",
    translating: "Übersetze...",
    translationError: "Übersetzung nicht verfügbar",
    myProjects: "Meine Projekte",
    addProject: "Projekt Hinzufügen",
    editProject: "Projekt Bearbeiten",
    projectTitle: "Projekttitel",
    projectDescription: "Beschreibung",
    projectUrl: "URL",
    projectType: "Typ",
    website: "Webseite",
    miniapp: "Mini App",
    channel: "Kanal",
    other: "Andere",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    noProjects: "Keine Projekte hinzugefügt",
    addFirstProject: "Füge dein erstes Projekt hinzu",
    manageProjects: "Füge Links zu deinen Projekten hinzu",
    sectionOrder: "Abschnittsreihenfolge",
    reorderSections: "Zum Sortieren ziehen",
    resetOrder: "Zurücksetzen",
    projectImage: "Vorschaubild",
    addManually: "Manuell hinzufügen",
    noImageYet: "Noch kein Bild",
    urlHelp: "Webseiten, Mini Apps oder Farcaster Kanäle (/kanal)",
    aboutMe: "Über Mich",
    editAboutMe: "Über Mich Bearbeiten",
    aboutMePlaceholder: "Erzähle mehr über dich, deine Interessen, woran du arbeitest...",
    charactersRemaining: "Zeichen übrig",
    noAboutMe: "Noch keine erweiterte Bio",
    addAboutMe: "Füge eine längere Bio hinzu, um deine Geschichte zu erzählen",
  },
  pt: {
    customizeProfile: "Personalizar Perfil",
    displayMode: "Modo de Exibição",
    darkMode: "Modo escuro",
    lightMode: "Modo claro",
    dark: "Escuro",
    light: "Claro",
    colorTheme: "Tema de Cor",
    fontStyle: "Estilo de Fonte",
    featuredContent: "Conteúdo em Destaque",
    featuredNFTs: "NFTs em Destaque",
    chooseNFTs: "Escolha quais NFTs mostrar",
    featuredCast: "Cast em Destaque",
    pickCast: "Escolha seu melhor cast",
    custom: "Personalizado",
    language: "Idioma",
    selectLanguage: "Selecione seu idioma",
    featuredNFTsTitle: "NFTs em Destaque",
    topHoldings: "Principais Ativos",
    topCast: "Melhor Cast",
    noNFTsFound: "Nenhum NFT Encontrado",
    noNFTsWallet: "Esta carteira não tem NFTs ainda",
    noVerifiedWallet: "Nenhum endereço verificado encontrado",
    noFeaturedCast: "Nenhum cast selecionado",
    viewOnWarpcast: "Ver no Warpcast →",
    today: "Hoje",
    yesterday: "Ontem",
    daysAgo: "dias atrás",
    weeksAgo: "semanas atrás",
    monthsAgo: "meses atrás",
    yearsAgo: "anos atrás",
    chooseCast: "Escolher Cast Principal",
    selectCastFeature: "Selecione um cast para destacar",
    fetchingCasts: "Buscando casts...",
    searched: "pesquisados",
    showingTop: "Mostrando os",
    castsByEngagement: "casts mais populares",
    fromTotal: "de",
    total: "total",
    noCastsFound: "Nenhum Cast Encontrado",
    noCastsEngagement: "Nenhum cast com engajamento ainda",
    done: "Pronto",
    selectNFTs: "Selecionar NFTs",
    chooseUpTo: "Escolha até",
    nftsToFeature: "NFTs para destacar",
    selected: "selecionados",
    loadingNFTs: "Carregando NFTs...",
    noNFTsInWallet: "Nenhum NFT nesta carteira",
    translate: "Traduzir",
    showOriginal: "Mostrar Original",
    translating: "Traduzindo...",
    translationError: "Tradução indisponível",
    myProjects: "Meus Projetos",
    addProject: "Adicionar Projeto",
    editProject: "Editar Projeto",
    projectTitle: "Título do Projeto",
    projectDescription: "Descrição",
    projectUrl: "URL",
    projectType: "Tipo",
    website: "Website",
    miniapp: "Mini App",
    channel: "Canal",
    other: "Outro",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    noProjects: "Nenhum projeto adicionado",
    addFirstProject: "Adicione seu primeiro projeto",
    manageProjects: "Adicione links para seus projetos",
    sectionOrder: "Ordem das Seções",
    reorderSections: "Arraste para reordenar",
    resetOrder: "Redefinir",
    projectImage: "Imagem de Pré-visualização",
    addManually: "Adicionar manualmente",
    noImageYet: "Sem imagem ainda",
    urlHelp: "Sites, mini apps ou canais Farcaster (/canal)",
    aboutMe: "Sobre Mim",
    editAboutMe: "Editar Sobre Mim",
    aboutMePlaceholder: "Conte às pessoas mais sobre você, seus interesses, no que está trabalhando...",
    charactersRemaining: "caracteres restantes",
    noAboutMe: "Ainda sem bio estendida",
    addAboutMe: "Adicione uma bio mais longa para contar sua história",
  },
  ja: {
    customizeProfile: "プロフィールをカスタマイズ",
    displayMode: "表示モード",
    darkMode: "ダークモード",
    lightMode: "ライトモード",
    dark: "ダーク",
    light: "ライト",
    colorTheme: "カラーテーマ",
    fontStyle: "フォントスタイル",
    featuredContent: "注目コンテンツ",
    featuredNFTs: "注目のNFT",
    chooseNFTs: "表示するNFTを選択",
    featuredCast: "注目のキャスト",
    pickCast: "最高のキャストを選択",
    custom: "カスタム",
    language: "言語",
    selectLanguage: "言語を選択してください",
    featuredNFTsTitle: "注目のNFT",
    topHoldings: "トップ保有",
    topCast: "トップキャスト",
    noNFTsFound: "NFTが見つかりません",
    noNFTsWallet: "このウォレットにはまだNFTがありません",
    noVerifiedWallet: "認証済みアドレスが見つかりません",
    noFeaturedCast: "キャストが選択されていません",
    viewOnWarpcast: "Warpcastで見る →",
    today: "今日",
    yesterday: "昨日",
    daysAgo: "日前",
    weeksAgo: "週間前",
    monthsAgo: "ヶ月前",
    yearsAgo: "年前",
    chooseCast: "トップキャストを選択",
    selectCastFeature: "プロフィールに表示するキャストを選択",
    fetchingCasts: "キャストを取得中...",
    searched: "検索済み",
    showingTop: "トップ",
    castsByEngagement: "エンゲージメント順",
    fromTotal: "件中",
    total: "件",
    noCastsFound: "キャストが見つかりません",
    noCastsEngagement: "エンゲージメントのあるキャストがありません",
    done: "完了",
    selectNFTs: "NFTを選択",
    chooseUpTo: "最大",
    nftsToFeature: "件のNFTを選択",
    selected: "件選択中",
    loadingNFTs: "NFTを読み込み中...",
    noNFTsInWallet: "このウォレットにNFTがありません",
    translate: "翻訳",
    showOriginal: "原文を表示",
    translating: "翻訳中...",
    translationError: "翻訳できません",
    myProjects: "マイプロジェクト",
    addProject: "プロジェクトを追加",
    editProject: "プロジェクトを編集",
    projectTitle: "プロジェクト名",
    projectDescription: "説明",
    projectUrl: "URL",
    projectType: "タイプ",
    website: "ウェブサイト",
    miniapp: "ミニアプリ",
    channel: "チャンネル",
    other: "その他",
    save: "保存",
    cancel: "キャンセル",
    delete: "削除",
    noProjects: "プロジェクトがありません",
    addFirstProject: "最初のプロジェクトを追加",
    manageProjects: "プロジェクトのリンクを追加",
    sectionOrder: "セクション順序",
    reorderSections: "ドラッグして並べ替え",
    resetOrder: "リセット",
    projectImage: "プレビュー画像",
    addManually: "手動で追加",
    noImageYet: "画像なし",
    urlHelp: "ウェブサイト、ミニアプリ、チャンネル（/チャンネル）対応",
    aboutMe: "自己紹介",
    editAboutMe: "自己紹介を編集",
    aboutMePlaceholder: "あなた自身、興味、取り組んでいることについて詳しく教えてください...",
    charactersRemaining: "文字残り",
    noAboutMe: "まだ詳細な自己紹介がありません",
    addAboutMe: "あなたの物語を伝える長い自己紹介を追加",
  },
  ko: {
    customizeProfile: "프로필 사용자 정의",
    displayMode: "디스플레이 모드",
    darkMode: "다크 모드",
    lightMode: "라이트 모드",
    dark: "다크",
    light: "라이트",
    colorTheme: "색상 테마",
    fontStyle: "폰트 스타일",
    featuredContent: "추천 콘텐츠",
    featuredNFTs: "추천 NFT",
    chooseNFTs: "표시할 NFT 선택",
    featuredCast: "추천 캐스트",
    pickCast: "최고의 캐스트 선택",
    custom: "사용자 정의",
    language: "언어",
    selectLanguage: "언어를 선택하세요",
    featuredNFTsTitle: "추천 NFT",
    topHoldings: "상위 보유",
    topCast: "상위 캐스트",
    noNFTsFound: "NFT를 찾을 수 없습니다",
    noNFTsWallet: "이 지갑에는 아직 NFT가 없습니다",
    noVerifiedWallet: "인증된 주소를 찾을 수 없습니다",
    noFeaturedCast: "선택된 캐스트가 없습니다",
    viewOnWarpcast: "Warpcast에서 보기 →",
    today: "오늘",
    yesterday: "어제",
    daysAgo: "일 전",
    weeksAgo: "주 전",
    monthsAgo: "개월 전",
    yearsAgo: "년 전",
    chooseCast: "상위 캐스트 선택",
    selectCastFeature: "프로필에 표시할 캐스트 선택",
    fetchingCasts: "캐스트 가져오는 중...",
    searched: "검색됨",
    showingTop: "상위",
    castsByEngagement: "참여도순 캐스트",
    fromTotal: "중",
    total: "개",
    noCastsFound: "캐스트를 찾을 수 없습니다",
    noCastsEngagement: "참여가 있는 캐스트가 없습니다",
    done: "완료",
    selectNFTs: "NFT 선택",
    chooseUpTo: "최대",
    nftsToFeature: "개의 NFT 선택",
    selected: "개 선택됨",
    loadingNFTs: "NFT 로딩 중...",
    noNFTsInWallet: "이 지갑에 NFT가 없습니다",
    translate: "번역",
    showOriginal: "원문 보기",
    translating: "번역 중...",
    translationError: "번역 불가",
    myProjects: "내 프로젝트",
    addProject: "프로젝트 추가",
    editProject: "프로젝트 편집",
    projectTitle: "프로젝트 제목",
    projectDescription: "설명",
    projectUrl: "URL",
    projectType: "유형",
    website: "웹사이트",
    miniapp: "미니앱",
    channel: "채널",
    other: "기타",
    save: "저장",
    cancel: "취소",
    delete: "삭제",
    noProjects: "프로젝트가 없습니다",
    addFirstProject: "첫 번째 프로젝트를 추가하세요",
    manageProjects: "프로젝트 링크 추가",
    sectionOrder: "섹션 순서",
    reorderSections: "드래그하여 재정렬",
    resetOrder: "초기화",
    projectImage: "미리보기 이미지",
    addManually: "수동으로 추가",
    noImageYet: "이미지 없음",
    urlHelp: "웹사이트, 미니앱 또는 채널 (/채널) 지원",
    aboutMe: "소개",
    editAboutMe: "소개 편집",
    aboutMePlaceholder: "자신, 관심사, 작업 중인 것에 대해 더 알려주세요...",
    charactersRemaining: "자 남음",
    noAboutMe: "아직 확장 소개가 없습니다",
    addAboutMe: "더 긴 소개를 추가하여 이야기를 전하세요",
  },
  zh: {
    customizeProfile: "自定义个人资料",
    displayMode: "显示模式",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    dark: "深色",
    light: "浅色",
    colorTheme: "颜色主题",
    fontStyle: "字体样式",
    featuredContent: "精选内容",
    featuredNFTs: "精选NFT",
    chooseNFTs: "选择要展示的NFT",
    featuredCast: "精选帖子",
    pickCast: "选择你最好的帖子",
    custom: "自定义",
    language: "语言",
    selectLanguage: "选择您的语言",
    featuredNFTsTitle: "精选NFT",
    topHoldings: "主要持仓",
    topCast: "热门帖子",
    noNFTsFound: "未找到NFT",
    noNFTsWallet: "此钱包还没有NFT",
    noVerifiedWallet: "未找到验证地址",
    noFeaturedCast: "未选择帖子",
    viewOnWarpcast: "在Warpcast查看 →",
    today: "今天",
    yesterday: "昨天",
    daysAgo: "天前",
    weeksAgo: "周前",
    monthsAgo: "个月前",
    yearsAgo: "年前",
    chooseCast: "选择热门帖子",
    selectCastFeature: "选择要展示的帖子",
    fetchingCasts: "获取帖子中...",
    searched: "已搜索",
    showingTop: "显示前",
    castsByEngagement: "个热门帖子",
    fromTotal: "共",
    total: "个",
    noCastsFound: "未找到帖子",
    noCastsEngagement: "还没有有互动的帖子",
    done: "完成",
    selectNFTs: "选择NFT",
    chooseUpTo: "最多选择",
    nftsToFeature: "个NFT展示",
    selected: "已选择",
    loadingNFTs: "加载NFT中...",
    noNFTsInWallet: "此钱包中没有NFT",
    translate: "翻译",
    showOriginal: "显示原文",
    translating: "翻译中...",
    translationError: "翻译不可用",
    myProjects: "我的项目",
    addProject: "添加项目",
    editProject: "编辑项目",
    projectTitle: "项目名称",
    projectDescription: "描述",
    projectUrl: "链接",
    projectType: "类型",
    website: "网站",
    miniapp: "小程序",
    channel: "频道",
    other: "其他",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    noProjects: "暂无项目",
    addFirstProject: "添加您的第一个项目",
    manageProjects: "添加项目链接",
    sectionOrder: "板块顺序",
    reorderSections: "拖动重新排序",
    resetOrder: "重置",
    projectImage: "预览图片",
    addManually: "手动添加",
    noImageYet: "暂无图片",
    urlHelp: "支持网站、小程序或频道（/频道）",
    aboutMe: "关于我",
    editAboutMe: "编辑关于我",
    aboutMePlaceholder: "告诉大家更多关于你的事情、你的兴趣、你在做什么...",
    charactersRemaining: "剩余字符",
    noAboutMe: "还没有扩展简介",
    addAboutMe: "添加更长的简介来讲述你的故事",
  },
};

export function useLanguage(fid: number | undefined) {
  const [language, setLanguageState] = useState<LanguageKey>("en");
  const [isLoaded, setIsLoaded] = useState(false);

  // Load language from localStorage on mount
  useEffect(() => {
    if (!fid) {
      setIsLoaded(true);
      return;
    }

    const storageKey = `${STORAGE_KEY_PREFIX}${fid}`;
    const stored = localStorage.getItem(storageKey);

    if (stored && stored in LANGUAGES) {
      setLanguageState(stored as LanguageKey);
    }

    setIsLoaded(true);
  }, [fid]);

  // Save language to localStorage
  const setLanguage = useCallback(
    (newLanguage: LanguageKey) => {
      if (!fid) return;

      setLanguageState(newLanguage);
      const storageKey = `${STORAGE_KEY_PREFIX}${fid}`;
      localStorage.setItem(storageKey, newLanguage);
    },
    [fid]
  );

  // Get translation function
  const t = useCallback(
    (key: string): string => {
      return TRANSLATIONS[language][key] || TRANSLATIONS.en[key] || key;
    },
    [language]
  );

  return {
    language,
    setLanguage,
    t,
    isLoaded,
    languages: LANGUAGES,
  };
}
